[project]
name = "certified-builder-api-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-typing>=2.20.0",
    "boto3>=1.40.9",
    "pydantic>=2.11.7",
]
